In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('KPK data set.xlsx')

In [4]:
df

GN  AG  MS  RS  ES  FI  ED  CI  F1  F2  ...  M1  M2   M3  D1  D2  D3  D4  \
0     0   1   0   0   0   3   3   1   1   1  ...   4   2  1.0   1   1   1   1   
1     1   2   0   1   1   3   2   0   2   2  ...   4   4  2.0   1   1   2   2   
2     0   3   1   1   1   3   4   0   3   4  ...   4   4  3.0   1   1   1   1   
3     0   2   1   1   1   3   2   1   2   4  ...   2   4  2.0   1   1   1   1   
4     0   2   1   1   1   3   2   1   2   3  ...   1   4  1.0   1   1   1   1   
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ...  ..  ..  ..  ..   
496   0   1   0   0   0   2   3   1   3   4  ...   3   5  2.0   1   1   1   2   
497   1   1   0   1   0   1   3   1   3   3  ...   4   3  2.0   1   1   1   1   
498   1   1   0   1   0   1   3   1   5   4  ...   2   4  1.0   2   2   4   2   
499   0   2   0   0   1   1   2   1   3   3  ...   4   4  2.0   1   1   1   1   
500   1   2   1   0   0   2   2   1   4   4  ...   5   4  3.0   1   1   1   1   

     D5  D6  D7  
0     1   1   1  
1     2   2   1  
2     1   1   1  
3     1   1   1  
4     1   1   1  
..   ..  ..  ..  
496   3   1   1  
497   1   3   1  
498   2   1   3  
499   1   1   1  
500   1   1   1  

[501 rows x 41 columns]

In [6]:
questions = {
    'GN':'Gender',
    'AG':'Age (in years)',
    'MS': 'Marital status',
    'RS':'Area of residence',
    'ES':'Employment status',
    'FI':'Monthly Family Income',
    'ED':'Level of Education',
    'CI':'Do you know any of your friend or family member who is infected with COVID-19?',
    'F1':'I am most afraid of Corona (COVID-19)',
    'F2':'It makes me uncomfortable to think about Corona',
    'F3':'My hands become clammy when I think about Corona',
    'F4':'I am afraid of losing my life because of Corona',
    'F5':'When I watch news and stories about Corona on social media, I become nervous or anxious',
    'F6':'I cannot sleep because Im worrying about getting Corona',
    'F7':'My heart races or palpitates when I think about getting Corona',
    'P1':'I regularly wash my hands for 20 seconds',
    'P2':'I wear mask when go outside',
    'P3':'I avoid handshake and physical gestures of greetings',
    'P4':'I maintain social/physical distance while meeting others',
    'P5':'I do not meet (or avoid) people who have cough or flue',
    'P6':'I do not touch my face (mouth, nose, eyes) without washing my hands',
    'P7':'When water is not available, I use sanitizer to clean my hands',
    'A1':'I am often a carefree and good spirit',
    'A2':'I enjoy my life',
    'A3':'All in all, I am satisfied with my life',
    'A4':'In general, I am confident',
    'A5':'I manage well to fulfil my needs',
    'A6':'I am in good physical and emotional condition',
    'A7':'I feel that I am actually well equipped to deal with life and its activities',
    'A8':'Much of what I do brings me joy',
    'A9':'I am a calm, balanced human being',
    'M1':'Are you satisfied with the steps taken by the government authorities to control the spread of Coronavirus?',
    'M2':'Are you satisfied with your familys safety from COVID-19?',
    'M3':'Are you satisfied with your studies during the prevailing situation of COVID-19?',
    'D1':'Over the last two weeks, feeling nervous, anxious, or on edge',
    'D2':'Over the last two weeks, not being able to stop or control worrying',
    'D3':'Over the last two weeks, worrying too much about different things',
    'D4':'Over the last two weeks, trouble relaxing',
    'D5':'Over the last two weeks, being so restless that it is hard to sit still',
    'D6':'Over the last two weeks, becoming easily annoyed or irritable',
    'D7':'Over the last two weeks, feeling afraid, as if something awful might happen'
}
    
    

In [8]:
df.D1.value_counts()

1    343
2    101
3     35
4     22
Name: D1, dtype: int64

In [13]:
df.shape

(501, 41)

In [9]:
X = df.drop(columns=['D1'])
y = df.D1

In [11]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [19]:
import xgboost as xgb

In [20]:
model = xgb.XGBClassifier()

In [21]:
model.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [23]:
model.predict(X_test)

array([2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4,
       1, 1, 2, 1, 3, 1, 1, 2, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 4], dtype=int64)

In [28]:
model.predict(X_test)

array([2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4,
       1, 1, 2, 1, 3, 1, 1, 2, 1, 1, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 4], dtype=int64)

In [32]:
sum(y_test == model.predict(X_test))/len(y_test)

0.8431372549019608

In [37]:
X_train.to_numpy()[0]

array([0., 1., 1., 0., 1., 3., 2., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 3., 4., 4., 4., 4., 3., 3., 4., 4., 2., 2., 2.,
       1., 1., 2., 2., 2., 1.])